update yml file: docker container

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -35,11 +35,9 @@ jobs:
     - name: Install dependencies
       run: go mod download
 
-
     - name: Build
       run: go build -v ./...
 
-    
     - name: Run go vet
       run: go vet ./...
 
@@ -47,7 +45,7 @@ jobs:
       run: go install golang.org/x/lint/golint@latest
 
     - name: Run golint
-      run: golint ./... | (! grep . -q) || (echo "Linting errors found" && false)
+      run: golint ./... | (! grep . -q) || (echo "Linting errors found" && false) 
 
     - name: Install gosec
       run: go install github.com/securego/gosec/v2/cmd/gosec@latest
@@ -57,3 +55,15 @@ jobs:
 
     - name: Run Tests
       run: go test ./... -v
+
+    # Docker build and push steps
+    - name: Login to Docker Hub
+      uses: docker/login-action@v1 
+      with:
+        username: ${{ secrets.DOCKER_HUB_USERNAME }}
+        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
+
+    - name: Build and push Docker image
+      run: |
+        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:latest .
+        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:latest
